
int main(){
	char letter = 'f';
	int number = 53;
	string word= "Hello World!";
	someInt++;
	int secondNumber = 47;
	printf(word);
	
	int addNumbers (int x, int y){
		int z = x + y;
		return z;
	}
	
	int sum = addNumbers(number, secondNumber);
	printf("The sum of the numbers was: \n", sum);
	sum++;
	sum--;
	sum /= 4;
	sum -= 25;
	sum += 3;
	sum *= 4;
	printf(sum);
	if (sum != 12){
		printf("something \t went \"wrong\" !");
	}
	else{
		printf("everything looks right!");
	}
	
	string wrong = "Oh no, something
			went wrong!";
	sting over = "This wont get
			closed;
	int notScanned = 3;
	char f = 'x';
}

